[Brute Force Detection]
search = index=idx_web sourcetype=access_combined status=401 | stats count by src_ip | where count > 5
dispatch.earliest_time = -5m
dispatch.latest_time = now
cron_schedule = */5 * * * *
enableSched = 1

alert.severity = 4
alert.suppress = 0
alert.track = 1
