[Brute Force Detection]
search = index="idx_web" status=401 | stats count by src_ip | where count > 5
dispatch.earliest_time = -5m
dispatch.latest_time = now
cron_schedule = */5 * * * *
enableSched = 1
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
alert.severity = 4
alert.suppress = 0
alert.track = 1

# 1. PROFESSIONAL MAİL AYARLARI (Sənin mailin bura əlavə olundu)
action.email = 1
action.email.to = splunkposeidox@gmail.com
action.email.subject = 🚨 [SOC ALERT] Brute Force Hücumu Təsbit Edildi!
action.email.message = 🚨 MILLISEC SOC ALERT\n\n🔴 TƏHLÜKƏ: HIGH\n📝 NÖV: Brute Force Detection\n👤 MƏNBƏ IP: $result.src_ip$\n📊 STATİSTİKA: Cəhd: $result.count$ | Status: 401\n🕒 VAXT: Məhz İndi\n\n_________________________
action.email.include.search_string = 0

# 2. TELEGRAM SKRİPTİNİN TƏTİKLƏNMƏSİ
action.script = 1
action.script.filename = telegram_alert.py
