name: Splunk Rule Deployer
on:
  push:
    paths:
      - 'rules/**'

jobs:
  deploy_to_splunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: API Call to Splunk
        run: |
          for file in rules/*.conf; do
            rule_name=$(basename "$file" .conf)
            search_query=$(cat "$file")
            
            echo "Deploying rule: $rule_name via API..."
            
            curl -k -X POST "https://${{ secrets.SPLUNK_HOST }}:8089/services/saved/searches" \
                 -H "Authorization: Bearer ${{ secrets.SPLUNK_TOKEN }}" \
                 -H "Content-Type: application/x-www-form-urlencoded" \
                 -d name="$rule_name" \
                 -d search="$search_query" \
                 -d alert_type="number of events" \
                 -d alert_comparator="greater than" \
                 -d alert_threshold="0" \
                 -d "action.webhook.enable=1" \
                 -d "is_scheduled=1" \
                 -d "cron_schedule=*/1 * * * *" \
                 -d "is_visible=1" \
                 -d "output_mode=json"
          done
